# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0003_auto_20160412_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('companyDescription', models.TextField()),
                ('companyWebsite', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('companyEmail', models.EmailField(max_length=75)),
                ('companyImage', models.ImageField(upload_to='company/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jobDescription', models.TextField()),
                ('skills', models.TextField()),
                ('postedDate', models.DateField(auto_now_add=True)),
                ('salaryRange', models.CharField(choices=[('1', 'Menos de 10,000'), ('2', '10,000 - 20,000'), ('3', '20,000 - 30,000'), ('4', '30,000 - 40,000'), ('5', '40,000 - 60,000'), ('6', '60,000 - 80,000'), ('7', '80,000 o superior')], max_length=1)),
                ('jobtype', models.CharField(choices=[('C', 'Tiempo Completo'), ('T', 'Temporal')], max_length=1)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ManyToManyField(blank=True, to='jobs.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Company')),
            ],
        ),
    ]
