# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='skills',
            field=models.TextField(default='tester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salaryRange',
            field=models.CharField(max_length=30),
        ),
    ]
