# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_remove_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='profile_images/%Y/%m/%d')),
                ('resume', models.FileField(help_text='PDF', upload_to='resumes/%Y/%m/%d')),
                ('summary', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, help_text='Agrega todas las formas en que podams contactarte', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
