# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='jobs',
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.Category'),
        ),
    ]
