# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20160418_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='place',
            field=models.CharField(default='foxconn', max_length=100),
            preserve_default=False,
        ),
    ]
