# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
        ('jobs', '0004_auto_20160321_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_profile.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='category',
            field=models.ManyToManyField(blank=True, to='jobs.Category'),
        ),
    ]
