# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_workexperience_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
