# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160321_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('companyDescription', models.TextField()),
                ('companyWebsite', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('companyImage', models.ImageField(upload_to='company/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='companyDescription',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='jobImage',
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobtype',
            field=models.CharField(choices=[('C', 'Tiempo Completo'), ('T', 'Temporal')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Company'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salaryRange',
            field=models.CharField(choices=[(1, 'Menos de 10,000'), (2, '10,000 - 20,000'), (3, '20,000 - 30,000'), (4, '30,000 - 40,000'), (5, '40,000 - 60,000'), (6, '60,000 - 80,000'), (7, '80,000 o superior')], max_length=1),
        ),
    ]
