# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20160322_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='user',
        ),
    ]
