# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0002_auto_20160322_0134'),
        ('jobs', '0007_remove_jobs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='company_profile.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salaryRange',
            field=models.CharField(choices=[('1', 'Menos de 10,000'), ('2', '10,000 - 20,000'), ('3', '20,000 - 30,000'), ('4', '30,000 - 40,000'), ('5', '40,000 - 60,000'), ('6', '60,000 - 80,000'), ('7', '80,000 o superior')], max_length=1),
        ),
    ]
