# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20160419_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(default='NPI Test Engineer', max_length=50),
            preserve_default=False,
        ),
    ]
