# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20160322_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
