# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0002_auto_20160322_0134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CompanyUser',
        ),
    ]
