# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='candidateuser',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='candidateuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='candidateuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidateuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
